
#ifndef SRC_GLOBAL_SETTINGS_H
#define SRC_GLOBAL_SETTINGS_H

#define SCALER_MAX_H_RES 4096
#define SCALER_MAX_V_RES 2160
#define MAX_LINE_BUFFERS 4

#define MAX_PIXELS_PER_CLOCK 2
#define MAX_COLORS_PER_PIXEL 3
#define MAX_BITS_PER_COLOR 8

#endif // SRC_GLOBAL_SETTINGS_H
